name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Flutter dependencies
      
        working-directory: ./YOUR_FLUTTER_PROJECT_DIRECTORY
      - name: Update CocoaPods repo
        run: pod repo update
        working-directory: ./YOUR_FLUTTER_PROJECT_DIRECTORY/ios 

      - name: Build iOS release
        run: flutter build ios --release --no-codesign
        working-directory: ./YOUR_FLUTTER_PROJECT_DIRECTORY 
      - name: Prepare Payload directory
        run: mkdir Payload
        working-directory: ./YOUR_FLUTTER_PROJECT_DIRECTORY/build/ios/iphoneos

      - name: Move app to Payload
        run: mv Runner.app/ Payload
        working-directory: ./YOUR_FLUTTER_PROJECT_DIRECTORY/build/ios/iphoneos

      - name: Create IPA file
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: ./YOUR_FLUTTER_PROJECT_DIRECTORY/build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./YOUR_FLUTTER_PROJECT_DIRECTORY/build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
